sonar.verbose=true
sonar.organization=pankajdemy01-key
sonar.projectKey=pankajdemy01-key_pankajdemytrend 
sonar.projectName=pankajdemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
